version: "3.9"
services:
  inventory-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.prod
    depends_on:
      - inventory_db

  inventory-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "4173:4173"
    env_file:
      - ./frontend/.env.prod
    depends_on:
      - inventory-backend

  inventory_db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_db
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  pgdata_prod:
