services:
  db:
    image: postgres:15
    container_name: inventory_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: inventory-backend
    volumes:
      - ./backend:/app
      - start.sh:/start.sh # ✅ Mount start.sh separately
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    # command: bash /start.sh

  frontend:
    build:
      context: ./frontend
    container_name: inventory-frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

volumes:
  pgdata:
