services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/inventory_db
      SECRET_KEY: "b55c8d5e72b267f259ae5a557cc35b74"
    depends_on:
      - db
    networks:
      - backend
      - proxy

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - proxy

volumes:
  db_data:

networks:
  backend:
  proxy:
